### ISSUE TITLE
Grass colour is not correctly changed

### ISSUE THREAD

**Issue by CSmither** [Coll1234567/NMSAddon#2]
When adding the following config to my biome config in terra all the colours change correctly except the grass colour.

```
colors:
  water: 0x7700ff
  water-fog: 0x39007a
  fog: 0xb16bff
  sky: 0xb16bff
  grass: 0x1f0042
  foliage: 0x39007a
```
![image](https://user-images.githubusercontent.com/19360936/141036876-b5de5596-8c18-457c-ad9b-c5ae6c81d173.png)
